from app.schemas.news import NewsAnalysis
from app.schemas.research import ReportSection, ResearchRequest, ResearchReport
from app.schemas.stocks import StockQuote
from app.tools.news_analysis import NewsDataError, get_news_analysis
from app.tools.stock_data import StockDataError, get_stock_quote


def build_mock_research_report(request: ResearchRequest) -> ResearchReport:
    ticker = request.ticker.upper()
    sections = [
        ReportSection(
            title="Business Overview",
            summary=(
                "This placeholder section will later be generated by an "
                "agent using company profile and filing context."
            ),
        ),
        _build_market_data_section(ticker),
        _build_news_sentiment_section(ticker),
    ]

    return ResearchReport(
        ticker=ticker,
        horizon=request.horizon,
        risk_level=request.risk_level,
        thesis=(
            f"{ticker} requires further analysis across market data, news, "
            "and SEC filings before a final investment decision."
        ),
        recommendation="watchlist",
        sections=sections,
        data_sources=["mock", "yfinance"],
    )


def _build_market_data_section(ticker: str) -> ReportSection:
    try:
        quote = get_stock_quote(ticker)
    except StockDataError as exc:
        return ReportSection(
            title="Market Data",
            summary=f"Market data is currently unavailable for {ticker}: {exc}",
        )

    return ReportSection(
        title="Market Data",
        summary=_summarize_quote(quote),
    )


def _summarize_quote(quote: StockQuote) -> str:
    parts = [
        f"{quote.ticker} latest available price is {_format_money(quote.price, quote.currency)}"
    ]

    if quote.previous_close is not None:
        change = quote.price - quote.previous_close
        change_pct = change / quote.previous_close * 100
        parts.append(
            "versus previous close "
            f"{_format_money(quote.previous_close, quote.currency)} "
            f"({_format_signed(change)} / {_format_signed(change_pct)}%)."
        )
    else:
        parts.append("with no previous close returned by the provider.")

    if quote.open is not None:
        parts.append(f"The session opened at {_format_money(quote.open, quote.currency)}.")

    if quote.day_low is not None and quote.day_high is not None:
        parts.append(
            "The reported intraday range is "
            f"{_format_money(quote.day_low, quote.currency)} to "
            f"{_format_money(quote.day_high, quote.currency)}."
        )

    if quote.volume is not None:
        parts.append(f"Latest reported volume is {quote.volume:,}.")

    return " ".join(parts)


def _build_news_sentiment_section(ticker: str) -> ReportSection:
    try:
        analysis = get_news_analysis(ticker)
    except NewsDataError as exc:
        return ReportSection(
            title="News Sentiment",
            summary=f"News analysis is currently unavailable for {ticker}: {exc}",
        )

    return ReportSection(
        title="News Sentiment",
        summary=_summarize_news_analysis(analysis),
    )


def _summarize_news_analysis(analysis: NewsAnalysis) -> str:
    headlines = "; ".join(analysis.key_headlines[:3])
    return f"{analysis.summary} Key headlines: {headlines}"


def _format_money(value: float, currency: str | None) -> str:
    prefix = "$" if currency == "USD" else ""
    suffix = "" if currency == "USD" or currency is None else f" {currency}"
    return f"{prefix}{value:,.2f}{suffix}"


def _format_signed(value: float) -> str:
    return f"{value:+.2f}"
